BASE_URL = 'https://www.tagesspiegel.de/'
IFRAME_SELECTOR = 'css=iframe#sp_message_iframe_1038892'
ACCEPT_ALL = '>>>    //button[@title="Alle akzeptieren"]'
FOCUS_MAIN_PAGE = 'xpath=//*[@id="page-container"]'
ANMELDEN_SELECTOR = '//*[@id="sso-menu"]/div/a/span/span'
REGISTRATION_IFRAME = 'css=iframe#modal-iframe'
REGISTRATION_BUTTON = '>>>    //button[@data-nav-item="register"]'
EMAIL_INPUT = '>>>    //*[@id="forms/formRegistration_email"]'
FIRST_NAME = '>>>    //*[@id="forms/formRegistration_forename"]'
LAST_NAME = '>>>    //*[@id="forms/formRegistration_surname"]'
REGISTRATION = '>>>    //button[@value="Jetzt registrieren"]'